version: '3.9'
name: 'pld'

services:
    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        platform: linux/amd64
        build: .docker/db
        ports:
            - "3307:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
            - mariadb_data:/var/log/mysql
            - mariadb_data:/etc/mysql/conf.d/my.cnf
            - mariadb_data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: laravel
            MYSQL_USER: usr
            MYSQL_PASSWORD: pass

    ####################################################################################################
    # REDIS
    ####################################################################################################
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
            - "6380:6379"
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - redis_data:/data

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        platform: linux/amd64
        image: phpmyadmin/phpmyadmin
        ports:
            - "8088:80"
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

    ####################################################################################################
    # PHP
    ####################################################################################################
    laravel:
        build: .docker/php
        ports:
            - "8080:5173"
        volumes:
            - ./Backend/:/var/www:cached
        depends_on:
            - db
            - redis

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - "8888:80"
        volumes:
            - ./Backend/:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - laravel

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        image: axllent/mailpit:latest
        ports:
        - "8025:8025"
        - "1025:1025"

volumes:
    mariadb_data:
        driver: local
    redis_data:
        driver: local